name: meter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.6.9
  connectivity_plus: ^6.1.4
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  flutter:
    sdk: flutter
  intl: ^0.20.2
  path_provider: ^2.1.5
  provider: ^6.1.4
  uuid: ^4.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.5.4
  hive_generator: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
